### ISSUE TITLE
What software is recommended to assemble homologous polyploid genomes to get contig?

### ISSUE THREAD

**Issue by fantasticair** [tanghaibao/allhic#10]
Hello,haibao
I saw your recent article, Assembly of allel-aware, chromosomal-scale
Autopolyploid genomes based on hi-c data, provides a new method for assembling the homologous polyploid genomes. I would like to ask you if there are any recommended software that can be better connected to your ALLHiC software by assembling.

Best wishes

**Comment by tangerzhang** [comment]
Hi,
Based on our experience, CANU is the best choice to assemble polyploid genome.

**Comment by fantasticair** [comment]
Thank you for your quick reply.
