### ISSUE TITLE
chromosome 0

### ISSUE THREAD

**Issue by mictadlo** [tanghaibao/allhic#12]
Hi, 
I ran ALLHIC successfully and I got my 19 chromosomes. However, I just wonder whether contigs that could not assign to a chromosome bin where stored e.g. in chromosome 0?

Thank you in advance,

Michal

**Comment by tangerzhang** [comment]
Hi Michal,
the contigs that are not assigned into chromosomes will be left with their original name and not stored in to chromosome 0.

**Comment by mictadlo** [comment]
Hi,
Where could I find contigs which were not assigned?

Thank you in advance, 

Michal

**Comment by tangerzhang** [comment]
Hi Michal,
You can find the unassigned contigs in agp file and also in the final assembly (groups.asm.fasta).

**Comment by mictadlo** [comment]
Hi,
I checked the below files but I could not find any unassigned contigs:
```
> grep ">" asm-19g.chr.fasta
>g1
>g2
>g3
>g4
>g5
>g6
>g7
>g8
>g9
>g10
>g11
>g12
>g13
>g14
>g15
>g16
>g17
>g18
>g19
```

```
> head  asm-19g.chr.agp
g1	1	376474	1	W	Backbone_1400	1	376474	-
g1	376475	376574	2	U	100	scaffold	yes	map
g1	376575	602644	3	W	Backbone_5375	1	226070	+
g1	602645	602744	4	U	100	scaffold	yes	map
g1	602745	784583	5	W	Backbone_13	1	181839	-
g1	784584	784683	6	U	100	scaffold	yes	map
g1	784684	825383	7	W	Backbone_5402	1	40700	+
g1	825384	825483	8	U	100	scaffold	yes	map
g1	825484	1006559	9	W	Backbone_1211	1	181076	+
g1	1006560	1006659	10	U	100	scaffold	yes	map
```

```
> tail asm-19g.chr.agp
g19	123078908	123079007	948	U	100	scaffold	yes	map
g19	123079008	123289635	949	W	Backbone_6115	1	210628	-
g19	123289636	123289735	950	U	100	scaffold	yes	map
g19	123289736	124955908	951	W	Backbone_151	1	1666173	+
g19	124955909	124956008	952	U	100	scaffold	yes	map
g19	124956009	125053529	953	W	Backbone_6769	1	97521	+
g19	125053530	125053629	954	U	100	scaffold	yes	map
g19	125053630	125112671	955	W	Backbone_9211	1	59042	+
g19	125112672	125112771	956	U	100	scaffold	yes	map
g19	125112772	125264581	957	W	Backbone_7103	1	151810	-
```

Did I miss anything?

Thank you in advance

Michal

**Comment by tangerzhang** [comment]
Hi Michal,
The anchored contigs can be found in the agp file. Why not extract the anchored contigs and then compare with the whole contig file to check which contigs are not anchored?
One possible reason is that all of the contigs are anchored to chromosomes and therefore no contigs are left.
