### ISSUE TITLE
value for partitions

### ISSUE THREAD

**Issue by mictadlo** [tanghaibao/allhic#2]
Hi  @tanghaibao and @tangerzhang, 
I have allotetraploid plant genome (3G) each haplotype should have 19 chromosomes. Is the value for partitions k = 19?

Thank you in advance,

Michal

**Comment by tangerzhang** [comment]
Hi Michal,
That depends on how many sets of haplotypes are assembled. If you are working on an allo-tetroploid genome, it is likely that two sets of haplotypes are assembled, similar like tobacco and cotton genomes. If so, K should be set to 19*2, i.e. 38.

**Comment by mictadlo** [comment]
Thank you.

**Comment by Juke34** [comment]
Hi @tangerzhang, should I count the organelles?
I.e I have a plant haploid genome = 10.
Should I use 10 or 11 for K because I guess one of the scaffold will be the chloroplast one.

**Comment by tangerzhang** [comment]
Hi @Juke34 
There is no need to count the organelles. The K value should be set to 10 in your case.
The chloroplast and mitochondria genomes should be left as unanchored sequences in ALLHiC results.
Alternative, you can remove the organelle sequences before running ALLHiC.
